name: phpo-nom-random
recipe: lamp
config:
  php: "8.2"
  webroot: ./public
  xdebug: "develop,debug"
services:
  appserver:
    config:
      php: ./.lando.config/php.ini
  database:
    portforward: 3307
    creds:
      user: admin
      password: admin
      database: nom-a-donner
      # Allez changer les valeur dans Core/App.php de la DB
